-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")

-- vim.api.nvim_create_autocmd("User", {
--   pattern = "LazyReload",
--   callback = function()
--     vim.schedule(function()
--       local core = require("plugins.core")
--       local colorscheme = nil
--       for _, plugin in ipairs(core) do
--         if plugin[1] == "LazyVim/LazyVim" and plugin.opts then
--           colorscheme = plugin.opts.colorscheme
--           break
--         end
--       end
--       if colorscheme then
--         vim.cmd.colorscheme(colorscheme)
--       end
--     end)
--   end,
-- })
